spring:
  datasource:
    url: jdbc:h2:mem:productsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create

  application.name: products

server:
  port: 8081