spring:
  datasource:
    url: jdbc:h2:mem:storesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  webclient:
    base-url: "http://localhost"

server:
  port: 8082
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b'

