spring:
  datasource:
    url: jdbc:h2:mem:storesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  webclient:
    base-url: "http://product-service"

server:
  port: 8082

